# Site settings
title: Brad Kwon
header-img: img/home-bg.jpg
email: junya815@gmail.com
copyright_name: Brad Kwon
description: "Brad Kwon's site"
baseurl: ""
url: "https://BradKwon.github.io"
#url: "http://localhost:4000"
#twitter_username: SBootstrap
github_username:  BradKwon
facebook_username:  hyeongu.kwon
email_username:  junya815@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-octicons]
