# Site settings
title: Brad Kwon
header-img: img/home-bg.jpg
email: junya815@gmail.com
copyright_name: Brad Kwon
description: "Brad Kwon's personal website. The introduction, the portfolio and blogs about programming and life of Brad Hyeongu Kwon."
baseurl: ""
url: "https://BradKwon.github.io"
#twitter_username: SBootstrap
linkedin_username: BradKwon
github_username:  BradKwon
facebook_username:  hyeongu.kwon
email_username:  junya815@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","vendor/bundle/","vendor/cache/","vendor/gems/","vendor/ruby"]

plugins: [jekyll-paginate-v2, jekyll-feed, jekyll-octicons, jekyll-seo-tag, jekyll-sitemap, jekyll-multiple-languages-plugin]

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true
  extension: html
  indexpage: 'index'
  title: ':title'
  debug: true

# jekyll-multiple-languages-plugin
languages: ["en", "ko"]
default_locale_in_subfolder: false
#exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]
