source 'https://rubygems.org'

group :jekyll_plugins do
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
  gem "jekyll-paginate-v2"
  gem "jekyll-feed"
  gem "jekyll-octicons"
  gem "jekyll"
end
